language: node_js
script: 'npm run build && npm start'
node_js:
  - '10'
cache: npm
env:
  - PAGE=800
  - PAGE=801
  - PAGE=802
  - PAGE=803
  - PAGE=804
  - PAGE=805
  - PAGE=806
  - PAGE=807
  - PAGE=808
  - PAGE=809
  - PAGE=810
  - PAGE=811
  - PAGE=812
  - PAGE=813
  - PAGE=814
  - PAGE=815
  - PAGE=816
  - PAGE=817
  - PAGE=818
  - PAGE=819
  - PAGE=820
  - PAGE=821
  - PAGE=822
  - PAGE=823
  - PAGE=824
  - PAGE=825
  - PAGE=826
  - PAGE=827
  - PAGE=828
  - PAGE=829
  - PAGE=830
  - PAGE=831
  - PAGE=832
  - PAGE=833
  - PAGE=834
  - PAGE=835
  - PAGE=836
  - PAGE=837
  - PAGE=838
  - PAGE=839
  - PAGE=840
  - PAGE=841
  - PAGE=842
  - PAGE=843
  - PAGE=844
  - PAGE=845
  - PAGE=846
  - PAGE=847
  - PAGE=848
  - PAGE=849
  - PAGE=850
  - PAGE=851
  - PAGE=852
  - PAGE=853
  - PAGE=854
  - PAGE=855
  - PAGE=856
  - PAGE=857
  - PAGE=858
  - PAGE=859
  - PAGE=860
  - PAGE=861
  - PAGE=862
  - PAGE=863
  - PAGE=864
  - PAGE=865
  - PAGE=866
  - PAGE=867
  - PAGE=868
  - PAGE=869
  - PAGE=870
  - PAGE=871
  - PAGE=872
  - PAGE=873
  - PAGE=874
  - PAGE=875
  - PAGE=876
  - PAGE=877
  - PAGE=878
  - PAGE=879
  - PAGE=880
  - PAGE=881
  - PAGE=882
  - PAGE=883
  - PAGE=884
  - PAGE=885
  - PAGE=886
  - PAGE=887
  - PAGE=888
  - PAGE=889
  - PAGE=890
  - PAGE=891
  - PAGE=892
  - PAGE=893
  - PAGE=894
  - PAGE=895
  - PAGE=896
  - PAGE=897
  - PAGE=898
  - PAGE=899
