language: node_js
script: 'npm run build && npm start'
node_js:
  - '10'
cache: npm
env:
  - PAGE=800
  - PAGE=801
  - PAGE=802
  - PAGE=803
  - PAGE=804
  - PAGE=805
  - PAGE=806
  - PAGE=807
  - PAGE=808
  - PAGE=809
  - PAGE=810
  - PAGE=811
  - PAGE=812
  - PAGE=813
  - PAGE=814
  - PAGE=815
  - PAGE=816
  - PAGE=817
  - PAGE=818
  - PAGE=819
  - PAGE=820
  - PAGE=821
  - PAGE=822
  - PAGE=823
  - PAGE=824
  - PAGE=825
  - PAGE=826
  - PAGE=827
  - PAGE=828
  - PAGE=829
  - PAGE=830
  - PAGE=831
  - PAGE=832
  - PAGE=833
  - PAGE=834
  - PAGE=835
  - PAGE=836
  - PAGE=837
  - PAGE=838
  - PAGE=839
  - PAGE=840
  - PAGE=841
  - PAGE=842
  - PAGE=843
  - PAGE=844
  - PAGE=845
  - PAGE=846
  - PAGE=847
  - PAGE=848
  - PAGE=849
  - PAGE=850
  - PAGE=851
  - PAGE=852
  - PAGE=853
  - PAGE=854
  - PAGE=855
  - PAGE=856
  - PAGE=857
  - PAGE=858
  - PAGE=859
  - PAGE=860
  - PAGE=861
  - PAGE=862
  - PAGE=863
  - PAGE=864
  - PAGE=865
  - PAGE=866
  - PAGE=867
  - PAGE=868
  - PAGE=869
  - PAGE=870
  - PAGE=871
  - PAGE=872
  - PAGE=873
  - PAGE=874
  - PAGE=875
  - PAGE=876
  - PAGE=877
  - PAGE=878
  - PAGE=879
  - PAGE=880
  - PAGE=881
  - PAGE=882
  - PAGE=883
  - PAGE=884
  - PAGE=885
  - PAGE=886
  - PAGE=887
  - PAGE=888
  - PAGE=889
  - PAGE=890
  - PAGE=891
  - PAGE=892
  - PAGE=893
  - PAGE=894
  - PAGE=895
  - PAGE=896
  - PAGE=897
  - PAGE=898
  - PAGE=899

undefined
a = ''
e = 900
for (var i = 0; i < 100; i++) {
  a+=`  - PAGE=${e+i}\n`
}
console.log(a)
VM391:6   - PAGE=900
  - PAGE=901
  - PAGE=902
  - PAGE=903
  - PAGE=904
  - PAGE=905
  - PAGE=906
  - PAGE=907
  - PAGE=908
  - PAGE=909
  - PAGE=910
  - PAGE=911
  - PAGE=912
  - PAGE=913
  - PAGE=914
  - PAGE=915
  - PAGE=916
  - PAGE=917
  - PAGE=918
  - PAGE=919
  - PAGE=920
  - PAGE=921
  - PAGE=922
  - PAGE=923
  - PAGE=924
  - PAGE=925
  - PAGE=926
  - PAGE=927
  - PAGE=928
  - PAGE=929
  - PAGE=930
  - PAGE=931
  - PAGE=932
  - PAGE=933
  - PAGE=934
  - PAGE=935
  - PAGE=936
  - PAGE=937
  - PAGE=938
  - PAGE=939
  - PAGE=940
  - PAGE=941
  - PAGE=942
  - PAGE=943
  - PAGE=944
  - PAGE=945
  - PAGE=946
  - PAGE=947
  - PAGE=948
  - PAGE=949
  - PAGE=950
  - PAGE=951
  - PAGE=952
  - PAGE=953
  - PAGE=954
  - PAGE=955
  - PAGE=956
  - PAGE=957
  - PAGE=958
  - PAGE=959
  - PAGE=960
  - PAGE=961
  - PAGE=962
  - PAGE=963
  - PAGE=964
  - PAGE=965
  - PAGE=966
  - PAGE=967
  - PAGE=968
  - PAGE=969
  - PAGE=970
  - PAGE=971
  - PAGE=972
  - PAGE=973
  - PAGE=974
  - PAGE=975
  - PAGE=976
  - PAGE=977
  - PAGE=978
  - PAGE=979
  - PAGE=980
  - PAGE=981
  - PAGE=982
  - PAGE=983
  - PAGE=984
  - PAGE=985
  - PAGE=986
  - PAGE=987
  - PAGE=988
  - PAGE=989
  - PAGE=990
  - PAGE=991
  - PAGE=992
  - PAGE=993
  - PAGE=994
  - PAGE=995
  - PAGE=996
  - PAGE=997
  - PAGE=998
  - PAGE=999
