language: node_js
script: 'npm run build && npm start'
node_js:
  - '10'
cache: npm
env:
  - PAGE=700
  - PAGE=701
  - PAGE=702
  - PAGE=703
  - PAGE=704
  - PAGE=705
  - PAGE=706
  - PAGE=707
  - PAGE=708
  - PAGE=709
  - PAGE=710
  - PAGE=711
  - PAGE=712
  - PAGE=713
  - PAGE=714
  - PAGE=715
  - PAGE=716
  - PAGE=717
  - PAGE=718
  - PAGE=719
  - PAGE=720
  - PAGE=721
  - PAGE=722
  - PAGE=723
  - PAGE=724
  - PAGE=725
  - PAGE=726
  - PAGE=727
  - PAGE=728
  - PAGE=729
  - PAGE=730
  - PAGE=731
  - PAGE=732
  - PAGE=733
  - PAGE=734
  - PAGE=735
  - PAGE=736
  - PAGE=737
  - PAGE=738
  - PAGE=739
  - PAGE=740
  - PAGE=741
  - PAGE=742
  - PAGE=743
  - PAGE=744
  - PAGE=745
  - PAGE=746
  - PAGE=747
  - PAGE=748
  - PAGE=749
  - PAGE=750
  - PAGE=751
  - PAGE=752
  - PAGE=753
  - PAGE=754
  - PAGE=755
  - PAGE=756
  - PAGE=757
  - PAGE=758
  - PAGE=759
  - PAGE=760
  - PAGE=761
  - PAGE=762
  - PAGE=763
  - PAGE=764
  - PAGE=765
  - PAGE=766
  - PAGE=767
  - PAGE=768
  - PAGE=769
  - PAGE=770
  - PAGE=771
  - PAGE=772
  - PAGE=773
  - PAGE=774
  - PAGE=775
  - PAGE=776
  - PAGE=777
  - PAGE=778
  - PAGE=779
  - PAGE=780
  - PAGE=781
  - PAGE=782
  - PAGE=783
  - PAGE=784
  - PAGE=785
  - PAGE=786
  - PAGE=787
  - PAGE=788
  - PAGE=789
  - PAGE=790
  - PAGE=791
  - PAGE=792
  - PAGE=793
  - PAGE=794
  - PAGE=795
  - PAGE=796
  - PAGE=797
  - PAGE=798
  - PAGE=799
